### ISSUE TITLE
VS 2019 Pro - Deprecated API

### ISSUE THREAD

**Issue by mshowman** [korypostma/BlackSpace#1]
![image](https://user-images.githubusercontent.com/17419707/57789497-09899a00-7707-11e9-9060-0a6f78f89c9d.png)

Wanted to make you aware of this.

**Comment by korypostma** [comment]
Hrmm, I'll have to open the project and figure out what is going on.  I wish this development of VSIX was much easier than what it is.  If anyone else gets to this first please submit a pull request as I'm not sure when I will be able to make it a priority to get this resolved.

**Comment by MarcKamradt** [comment]
I gave it a try: https://github.com/korypostma/BlackSpace/pull/2

**Comment by Toddler-Boy** [comment]
Please merge this.

**Comment by korypostma** [comment]
Sorry for the long delay guys, so many other things were much more important.  I gave up on trying to keep this working with VS2015, even my day job moved on to VS2019.  So I didn't merge the PR exactly because of a few different things but I corrected most of it.  Thanks so much @MarcKamradt for the help there.
